### ISSUE TITLE
Node ordering issue

### ISSUE THREAD

**Issue by razimantv** [arnaudon/netSALT#29]
https://github.com/arnaudon/netSALT/blob/3c48f14ddcaafcf8ff62a63d221df5c8334bf944/netsalt/tasks/passive.py#L69

This line assumes that node u is the uth element of quantum_graph.nodes. This is not the case since nx.nodes is not a sorted container.

**Comment by razimantv** [comment]
I thought of solving it by simply using sorted(quantum_graph.nodes) but I think the node numbers don't even need to be consecutive. We might have to use some internal numbering and map all nodes and edges to that one.

**Comment by arnaudon** [comment]
Here is the fix: https://github.com/arnaudon/netSALT/pull/30
